apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: infra-wayne
  name: infra-wayne
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infra-wayne
  template:
    metadata:
      labels:
        app: infra-wayne
    spec:
      volumes:
      - name: config
        configMap:
          name: infra-wayne
      containers:
      - name: wayne
        image: '360cloud/wayne:latest'
        command:
          - /opt/wayne/backend
          - apiserver
        env:
          - name: GOPATH  # app.conf runmode = dev must set GOPATH
            value: /go
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.5'
            memory: 1Gi
        volumeMounts:
          - name: config
            mountPath: /opt/wayne/conf/
        readinessProbe:
          httpGet:
            path: healthz
            port: 8080
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        imagePullPolicy: Always

