apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: wayne-backend
  name: wayne-backend
  namespace: default
data:
  app.conf: |-
    appname = wayne
    httpport = 8080
    runmode = prod
    autorender = false
    copyrequestbody = true
    EnableDocs = true
    EnableAdmin = true
    StaticDir = public:static

    # Custom config
    ShowSql = false

    ## if enable username and password login
    EnableDBLogin = true

    # token, generate jwt token
    RsaPrivateKey = "./apikey/rsa-private.pem"
    RsaPublicKey = "./apikey/rsa-public.pem"

    # token end time. second
    TokenLifeTime=86400

    # kubernetes labels config
    AppLabelKey= wayne-app
    NamespaceLabelKey = wayne-ns
    PodAnnotationControllerKindLabelKey = wayne.cloud/controller-kind

    # database configuration:
    ## mysql
    DBName = "wayne"
    DBTns = "tcp(mysql-wayne:3306)"
    DBUser = "root"
    DBPasswd = "root"
    DBConnTTL = 30

    # web shell auth
    appKey = "860af247a91a19b2368d6425797921c6"

    # Set demo namespace and group id
    DemoGroupId = "1"
    DemoNamespaceId = "1"

    # Sentry
    LogLevel = "4"
    SentryEnable = false
    SentryDSN = ""
    SentryLogLevel = "4"

    # Robin
    EnableRobin = false

    # api-keys
    EnableApiKeys = true

    # Bus
    BusEnable = false

    # Webhook
    EnableWebhook = true
    WebhookClientTimeout = 10
    WebhookClientWindowSize = 16

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wayne-backend
  name: wayne-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayne-backend
  template:
    metadata:
      labels:
        app: wayne-backend
    spec:
      volumes:
      - name: config
        configMap:
          name: wayne-backend
      containers:
      - name: wayne
        image: '360cloud/wayne-backend:v1.8.4-16-gf3a7366'
        command:
        - /opt/wayne/backend
        env:
        - name: GOPATH  # app.conf runmode = dev must set GOPATH
          value: /go
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.5'
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /opt/wayne/conf/
        readinessProbe:
          httpGet:
            path: healthz
            port: 8080
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wayne-backend
  name: wayne-backend
  namespace: default
spec:
  type: NodePort
  ports:
  - nodePort: 32001
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: wayne-backend
