apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: wayne-frontend
  name: wayne-frontend
  namespace: default
data:
  config.js: |-
    window.CONFIG = {
      URL: 'http://wayne.backend:32001',
      RAVEN: false,
      RAVEN_DSN: 'RAVEN_DSN'
    };

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wayne-frontend
  name: wayne-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayne-frontend
  template:
    metadata:
      labels:
        app: wayne-frontend
    spec:
      volumes:
      - name: config
        configMap:
          name: wayne-frontend
          items:
          - key: config.js
            path: config.js
      containers:
      - name: wayne
        image: '360cloud/wayne-frontend:latest'
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.5'
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /usr/local/openresty/nginx/html/config.js
          subPath: config.js
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wayne-frontend
  name: wayne-frontend
  namespace: default
spec:
  type: NodePort
  ports:
  - nodePort: 32000
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: wayne-frontend