version: '3'

services:

  mysql:
    image: mysql:5.6.41
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
    - default
    expose:
    - "3306"
    ports:
    - "3306:3306"

  wayne-backend:
    image: 360cloud/wayne-backend:v1.8.4-16-gf3a7366  
    command: /opt/wayne/backend
    environment:
      GOPATH: "/go"
    volumes:
    - ./conf/app.conf:/opt/wayne/conf/app.conf
    depends_on:
    - mysql
    restart: always
    networks:
    - default
    ports:
    - "8080:8080"

  wayne-frontend:
    image: 360cloud/wayne-frontend:latest
    volumes:
    - ./conf/config.js:/usr/local/openresty/nginx/html/config.js
    depends_on:
    - wayne-backend
    restart: always
    networks:
    - default
    ports:
    - "4200:80"


